set syntax=on
set shiftwidth=4
set tabstop=4
set smartindent
"map <F5> :set tags=/home/UT/HA/code/tags
set showcmd " show the command being typed
set showmatch " show matching brackets
set laststatus=2 " always show the status line
set lazyredraw " do not redraw while running macros
set linespace=0 " don't insert any extra pixel lines betweens rows
set list! " we do what to show tabs, to ensure we get them out of my files
set listchars=tab:>-,trail:- " show tabs and trailing
set matchtime=5 " how many tenths of a second to blink matching brackets for
set nostartofline " leave my cursor where it was
set novisualbell " don't blink
set report=0 " tell us when anything is changed via :...
set ruler " Always show current positions along the bottom
set number
set paste
set expandtab
set shell=bash
set fileformats=unix
filetype on                   " Enable filetype detection
filetype indent on            " Enable filetype-specific indenting
filetype plugin on            " Enable filetype-specific plugins
colorscheme evening
"  searching
set incsearch                 " incremental search
set hlsearch                  " highlight the search
set showmatch                 " show matching bracket
set diffopt=filler,iwhite     " ignore all whitespace and sync
set history=200
set backspace=indent,eol,start
set linebreak
set cmdheight=2               " command line two lines high
set undolevels=1000           " 1000 undos
set updatecount=100           " switch every 100 chars
set complete=.,w,b,u,U,t,i,d  " do lots of scanning on tab completion
set ttyfast                   " we have a fast terminal
set noerrorbells              " No error bells please
set nolist
 
" gVim configs
set guifont=Monospace\ 16
vmap <C-c> "+yi
vmap <C-x> "+c
vmap <C-v> c<ESC>"+p
imap <C-v> <ESC>"+pa
vmap <S-Insert> c<ESC>"+p
imap <S-Insert> <ESC>"+pa
